delete from Customers where id = 2; 
delete from Customers where id in (1,2,3);
delete from vehicles; 
delete from products where id = 2;
delete from Products where stock < 0;
delete from product_reviews where id =1;
delete from vehicles where in_service = 0;
delete from service_feedback where service_rating < 1; 
delete from product_reviews where comment_review is null;
delete from return_requests where reason is null;