update Customers set name = 'David Smith' where id = 1;
update Customers set email = 'daveSmithy@gmail.com' where id =1; 
update Customers set name =  'Liz Katz', email = 'lizzy@gmail.com' where id =2; 
update Customers set address = '9020 Boston' where id = 3;
update Products set price = 25.73 where id = 1;
update Products set description = '40 fluid ounce, Insulated stainless steel water bottle, 100% BPA free!! ' where id = 2;
update Products set stock = stock -1 where id =1;
update orders set delivery_date = null where id in (1);
update deliveries set status = 'processing' where id in (2);
update deliveries set status = 'delivered' where id in (1);