update Customers set customer_name = 'David Smith' where customer_id = 1;
update Customers set contact_details = 'daveSmithy@gmail.com' where customer_id =1; 
update Customers set customer_name =  'Liz Katz', contact_details = 'lizzy@gmail.com' where customer_id =2; 
update Customers set address = '9020 Boston' where customer_id = 3;
update Products set price = 25.73 where product_id = 1;
update Products set product_description = '40 fluid ounce, Insulated stainless steel water bottle, 100% BPA free!! ' where product_id = 2;
update Products set stock_quantity = stock_quantity-1 where product_id =1;
update orders set delivery_date = null where order_id in (1);
update orders set order_status = 'processing' where order_id in (2);
update orders set order_status = 'delivered' where order_id in (1);